### ISSUE TITLE
NIH

### ISSUE THREAD

**Issue by alexeyshockov** [ksassnowski/option#1]
The optional value concept is interesting and useful, but why do you need yet another library when https://github.com/schmittjoh/php-option is already here for a few years?

**Comment by ksassnowski** [comment]
This package was never really intended to be used in production. Is was sort of a coding exercise to myself how I would implemented it in PHP. I guess I should add that disclaimer to the Readme.

**Comment by alexeyshockov** [comment]
Thanks, now it's clear :)

👍
